package bgu.spl.net.impl.stomp;

import java.util.HashMap;
import java.util.Map;

public class StompFrame {

    private String command;
    private Map<String, String> headers = new HashMap<>();
    private String body;

    public StompFrame(String command, Map<String, String> headers, String body) {
        this.command = command;
        this.headers = headers;
        this.body = body;
    }

    /**
     * Parses a raw STOMP message string into a StompFrame object.
     * Assumes the input string contains the headers and body.
     */
    public static StompFrame fromString(String msg) {
        String[] lines = msg.split("\n");
        String command = "";
        Map<String, String> headers = new HashMap<>();
        StringBuilder bodyBuilder = new StringBuilder();
        
        int i = 0;
        
        // Parse command
        if (i < lines.length) {
            command = lines[i].trim();
            i++;
        }

        // Parse headers
        while (i < lines.length) {
            String line = lines[i];
            // Stop at the empty line indicating end of headers
            if (line.trim().isEmpty()) {
                i++;
                break;
            }

            int colonIndex = line.indexOf(':');
            if (colonIndex != -1) {
                String key = line.substring(0, colonIndex).trim();
                String value = line.substring(colonIndex + 1).trim();
                headers.put(key, value);
            }
            i++;
        }

        // 3. Read Body (append all remaining lines)
        while (i < lines.length) {
            bodyBuilder.append(lines[i]);
            if (i < lines.length - 1) {
                bodyBuilder.append("\n"); // Restore newlines in body
            }
            i++;
        }
        
        // Remove strict null terminator if present in the parsed string
        String bodyStr = bodyBuilder.toString().replace("\u0000", "");

        return new StompFrame(command, headers, bodyStr);
    }

    /**
     * Creates a CONNECTED frame.
     */
    public static StompFrame createConnectedFrame() {
        Map<String, String> headers = new HashMap<>();
        headers.put("version", "1.2");
        return new StompFrame("CONNECTED", headers, "");
    }

    /**
     * Creates a MESSAGE frame
     * @param subscriptionId The client's subscription ID.
     * @param messageId A unique ID for this message generated by the server.
     * @param destination The channel name.
     * @param body The actual message content.
     */
    public static StompFrame createMessageFrame(String subscriptionId, String messageId, String destination, String body) {
        Map<String, String> headers = new HashMap<>();
        headers.put("subscription", subscriptionId);
        headers.put("message-id", messageId);
        headers.put("destination", destination);
        return new StompFrame("MESSAGE", headers, body);
    }

    /**
     * Creates a RECEIPT frame.
     * @param receiptId The receipt-id requested by the client.
     */
    public static StompFrame createReceiptFrame(String receiptId) {
        Map<String, String> headers = new HashMap<>();
        headers.put("receipt-id", receiptId);
        return new StompFrame("RECEIPT", headers, "");
    }

    /**
     * Creates an ERROR frame.
     * @param message Description of the error.
     * @param detailedBody Detailed explanation or the content of the malformed frame.
     * @param receiptId The receipt-id of the frame that caused the error (might be empty).
     */
    public static StompFrame createErrorFrame(String message, String detailedBody, String receiptId) {
        Map<String, String> headers = new HashMap<>();
        headers.put("message", message);
        if (receiptId != null) {
            headers.put("receipt-id", receiptId);
        }
        return new StompFrame("ERROR", headers, detailedBody);
    }

    public String getCommand() {
        return command;
    }

    public Map<String, String> getHeaders() {
        return headers;
    }

    public String getBody() {
        return body;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(command).append("\n");
        
        for (Map.Entry<String, String> header : headers.entrySet()) {
            sb.append(header.getKey()).append(":").append(header.getValue()).append("\n");
        }
        
        sb.append("\n"); // Blank line to separate headers from body
        sb.append(body);
        // Java null terminator '\0' is "\u0000" in unicode
        sb.append("\u0000"); 
        
        return sb.toString();
    }
}